[p5.js hi] events references
processing/p5.js-website pull request #314
Opened 2024-04-29 14:18 UTC by Surbhi-Pittie

2024-04-30 13:54 UTC, Divyansh013 requested changes

2024-04-30 13:54 UTC, Divyansh013 commented on src/content/reference/hi/p5/doubleClicked.mdx
> +  जल्दी.</p>
जल्दी कॉल किया जाता है  should be write imo

2024-04-30 13:54 UTC, Divyansh013 commented on src/content/reference/hi/p5/doubleClicked.mdx
> +  दौड़ना
code 'chalne' would be write here

2024-04-30 13:54 UTC, Divyansh013 commented on src/content/reference/hi/p5/keyPressed.mdx
> +    यदि (कुंजी === 'सी') {
should be 'c' only

2024-04-30 13:54 UTC, Divyansh013 commented on src/content/reference/hi/p5/keyReleased.mdx
> +  फ़ंक्शन कुंजी जारी() {
don't change

2024-04-30 13:54 UTC, Divyansh013 commented on src/content/reference/hi/p5/keyTyped.mdx
> +  फ़ंक्शन कुंजी टाइप किया गया() {
keep function as it is

2024-05-01 17:25 UTC, Divyansh013 approved these changes

2024-05-02 07:45 UTC, Divyansh013 commented
@TanviKumar PTAL

2024-05-02 08:06 UTC, TanviKumar approved these changes

2024-05-02 16:40 UTC, Divyansh013 commented
@Qianqianye @limzykenneth we can merge this PR

2024-05-02 20:26 UTC, merged

2024-05-02 20:27 UTC, Qianqianye commented
Looks great, thank you all!