zh-Hans 3D (orbitControl ~ metalness)
processing/p5.js-website pull request #315
Opened 2024-04-29 16:34 UTC by Harrycheng233

2024-04-30 03:33 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/TEXTURE.mdx
> -      describe('A spinning cube with an image of a ceiling on each face.');
代码本身无需翻译。

2024-04-30 03:33 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/TEXTURE.mdx
> -      describe('A spinning cube with circle at the center of each face.');
代码本身无需翻译。

2024-04-30 03:33 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/TEXTURE.mdx
> -      describe('A rectangle with video as texture');
代码本身无需翻译。

2024-04-30 03:34 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/TEXTURE.mdx
> +      describe('一个视频作为纹理的矩形');
代码本身无需翻译。

2024-04-30 03:35 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/textureWrap.mdx
> -        'Four identical images of a landscape arranged in a grid. The top row and bottom row are reflections of each other.'
代码本身无需翻译。

2024-04-30 03:35 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/textureWrap.mdx
> +        '四幅相同的风景图像排列成网格。图像在水平和垂直方向上都被镜像，并产生万花筒效应。'
代码本身无需翻译。

2024-04-30 03:35 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/textureWrap.mdx
> +      describe('一个以网格排列的风景图像，四个图像都是相同的。');
代码本身无需翻译。

2024-04-30 03:36 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/textureWrap.mdx
> +        '一张风景图像占据了正方形的左上角。其边缘颜色渐变以覆盖正方形的其他三个角落。'
代码本身无需翻译。

2024-04-30 03:37 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/textureMode.mdx
> +      describe('一张天花板在黑色背景下的图片。');
代码本身无需翻译。

2024-04-30 03:37 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/textureMode.mdx
> +      describe('一张天花板在黑色背景下的图片。');
代码本身无需翻译。

2024-04-30 03:38 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/spotLight.mdx
> +      describe('一个绘制在灰色背景上的白色球体。用户双击时，红色聚光灯开始发光。');
代码本身无需翻译。

2024-04-30 03:38 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/spotLight.mdx
> +      describe('一个绘制在灰色背景上的白色球体。用户双击时，红色聚光灯开始发光。');
代码本身无需翻译。

2024-04-30 03:38 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularMaterial.mdx
> +        '一个红色的圆环绘制在灰色背景上。当用户双击时，它变得有光泽并反射绿色光。'
代码本身无需翻译。

2024-04-30 03:39 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularMaterial.mdx
> +        '一个红色的圆环绘制在灰色背景上。当用户双击时，它变得有光泽并反射绿色光。'
代码本身无需翻译。

2024-04-30 03:39 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularMaterial.mdx
> +      describe('一个红色的圆环绘制在灰色背景上。当用户双击时，它将变得有光泽。');
代码本身无需翻译。

2024-04-30 04:00 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientLight.mdx
> +      describe('一个绘制在灰色背景上的球体。当用户双击时，球体会改变其颜色。');
代码本身无需翻译。

2024-04-30 04:00 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientLight.mdx
> +      describe('在灰色背景上绘制了一个褪色的品红色球体。');
代码本身无需翻译。

2024-04-30 04:00 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientLight.mdx
> +      describe('一个绘制在灰色背景上的褪色的品红色球体。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientLight.mdx
> +      describe('一个绘制在灰色背景上的褪色的品红色球体。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientMaterial.mdx
> +      describe('一个品红色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientMaterial.mdx
> +      describe('一个紫色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientMaterial.mdx
> +      describe('一个红色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientMaterial.mdx
> +      describe('一个红色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientMaterial.mdx
> +      describe('一个红色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientMaterial.mdx
> +      describe('一个黄色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createFilterShader.mdx
> +      describe('深蓝色砖块的图像');
代码本身无需翻译。

2024-04-30 04:01 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createShader.mdx
> +      describe('一个黄色的正方形。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createShader.mdx
> +      describe('品红色背景上的黑色分形图像。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createShader.mdx
> +      describe('');
请复原原文

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/debugMode.mdx
> +      describe('一个多种颜色的方块放置在灰色背景上。方块附近显示了网格和坐标轴图标。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/debugMode.mdx
> +      describe('一个多种颜色的方块放置在灰色背景上。方块附近显示了网格和坐标轴图标。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/debugMode.mdx
> +      describe('一个多种颜色的盒子放在灰色背景上。盒子下方显示了一个网格。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/debugMode.mdx
> +      describe('一个多彩的盒子放在灰色背景上。盒子下方显示了一个网格。一个坐标轴图标显示在盒子的中心。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/directionalLight.mdx
> +      describe('在灰色背景上绘制的球体。当用户双击时，从上方开始发出红光。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/directionalLight.mdx
> +      describe('在灰色背景上绘制的球体。球体顶部呈亮红色。颜色朝底部变暗。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/directionalLight.mdx
> +      describe('在灰色背景上绘制的球体。球体顶部呈亮红色。颜色朝底部变暗。');
代码本身无需翻译。

2024-04-30 04:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/emissiveMaterial.mdx
> +      describe('一个红色的立方体绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/imageLight.mdx
> +      describe('一个悬浮在环境上方的球体。球体的表面反射着环境。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/lightFalloff.mdx
> +      describe('绘制在灰色背景上的球体。当用户双击时，光的强度会发生变化。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/lights.mdx
> +      describe('一个白色盒子绘制在灰色背景上。当用户双击时，光线的质量会发生变化。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/lights.mdx
> +      describe('一个白色盒子绘制在灰色背景上。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/loadShader.mdx
> +      describe('一个在品红色背景上的黑色分形图像。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/metalness.mdx
> +        '两个蓝色的球绘制在灰色背景上。当鼠标移动时，它们的表面反射出白色光。右侧的球比左侧的球更具金属感。'
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/metalness.mdx
> +        '两个悬浮在风景上方的球体。球体的表面反射出风景。右侧的球比左侧的球更具反射性。'
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/noDebugMode.mdx
> +      describe('一个多彩的方块放在灰色背景上。方块附近显示了网格和坐标轴图标。当用户双击时，它们会消失。');
代码本身无需翻译。

2024-04-30 04:03 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/noLights.mdx
> +      describe('两个球在灰色背景上绘制。顶部的球是白色的，底部的球是红色的。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/normalMaterial.mdx
> +      describe('在灰色背景上绘制一个多彩的圆环体。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/orbitControl.mdx
> +      describe('一个多种颜色的盒子置于灰色背景上。 当用户使用鼠标、触控板或触摸屏进行交互时，摄像机角度会发生变化。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/orbitControl.mdx
> +      describe('一个多种颜色的盒子置于灰色背景上。 当用户使用鼠标、触控板或触摸屏进行交互时，摄像机角度会发生变化。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/orbitControl.mdx
> +      describe('一个多种颜色的盒子置于灰色背景上。 当用户使用鼠标、触控板或触摸屏进行交互时，摄像机角度会发生变化。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/panorama.mdx
> +      describe('一个悬浮在环境上方的球体。球体的表面反射着环境。用户拖动鼠标时，可以以 3D 方式查看整个环境。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/pointLight.mdx
> +      describe('在灰色背景上绘制的球体。当用户双击时，从上方开始发出红光。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/pointLight.mdx
> +      describe('在灰色背景上绘制的球体。球体顶部呈亮红色。颜色朝底部变暗。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/pointLight.mdx
> +      describe('在灰色背景上绘制的球体。球体顶部呈亮红色。颜色朝底部变暗。');
代码本身无需翻译。

2024-04-30 04:04 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/pointLight.mdx
> +      describe('在灰色背景上绘制的四个球体。球体排列成一个正方形。正方形中心的球体呈亮红色。颜色朝四个角落渐暗。');
代码本身无需翻译。

2024-04-30 04:05 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/resetShader.mdx
> +        '灰色背景上的两个旋转立方体。 左边的每个面上都有蓝紫色渐变。 右边的是红色的。'
代码本身无需翻译。

2024-04-30 04:05 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/shader.mdx
> +      describe('一个黄色的正方形。');
代码本身无需翻译。

2024-04-30 04:05 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/shader.mdx
> +      describe('分形图像会放大和失焦。');
代码本身无需翻译。

2024-04-30 04:05 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/shader.mdx
> +        '当用户双击时，场景在两个圆形渐变之间切换。 橙色和蓝色渐变垂直，红色和绿色渐变水平移动。'
代码本身无需翻译。

2024-04-30 04:05 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/shininess.mdx
> +        '两个红色的球绘制在灰色背景上。当鼠标移动时，它们的表面反射出白色光。右侧的球比左侧的球更有光泽。'
代码本身无需翻译。

2024-04-30 04:11 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +      describe('在灰色背景上绘制了一个白色的球体。');
代码本身无需翻译。

2024-04-30 04:12 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +      describe('在灰色背景上绘制了一个球体。当用户双击时，聚光灯开始发光。');
代码本身无需翻译。

2024-04-30 04:12 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +      describe('在灰色背景上绘制一个黑色的球体。球体表面的一个区域以蓝色突出显示。');
代码本身无需翻译。

2024-04-30 04:12 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +      describe('在灰色背景上绘制了一个黑色的球体。球体表面的一个区域以蓝色突出显示。');
代码本身无需翻译。

2024-04-30 04:12 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +      describe('在灰色背景上绘制了一个黑色的球体。球体表面的一个区域以蓝色突出显示。');
代码本身无需翻译。

2024-04-30 10:22 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/ambientLight.mdx
> +  <p>创建一个从所有方向发光的灯光。</p>
创建一个从所有方向发光的灯光。-> 创建一个向所有方向发光的光源。

2024-04-30 10:36 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createFilterShader.mdx
> +  <p><code>createFilterShader()</code> 的工作方式与 <a href="/reference/p5/createShader">createShader()</a> 类似，但包含默认的顶点着色器。 <code>createFilterShader()</code> 旨在与 <a href="/reference/p5/filter">filter()</a>
一起使用来过滤画布的内容。 -> 一起使用来为画布的内容添加滤镜。

2024-04-30 10:38 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createFilterShader.mdx
> +  <li><code>vec2 texelSize</code>，这是物理像素的大小，包括像素密度。 像素宽度的计算方式为 <code>1.0 / (width * Density)</code>，像素高度的计算方式为 <code>1.0 / (Height * Density)</code>。</li>
<code>1.0 / (height * density)</code> 

如使用原文则不用改动原文，包括大小写。

2024-04-30 10:38 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/createFilterShader.mdx
> +  <p>创建的 <a href="/reference/p5/p5.Shader">p5.Shader</a> 还提供了<code>varyingvec2 vTexCoord</code>，这是一个值介于 0 和 1 <code>vTexCoord 之间的坐标，描绘像素在画布上绘制的位置。</p>
<code>vTexCoord</code>

后面的 </code> tag 未添加完整。

2024-04-30 10:40 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/debugMode.mdx
> +  <p>添加网格和轴标志以帮助明确3D绘图中的方向。</p>
中英文间隔，请检查一下所有译文避免前后不一致。

2024-04-30 10:49 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +  <p>调用 <code>specularColor()</code> 的第三种方式具有四个可选参数， <code>v1</code>, <code>v2</code>, <code>v3</code>, 和 <code>alpha</code>。 RGBA, HSBA, 或 HSLA 值，例如 <code>specularColor(255, 0, 0, 80)</code>, 可用于设置高
RGBA, HSBA, 或 HSLA 值，-> 使用中文顿号。

2024-04-30 10:50 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/specularColor.mdx
> +  <p>第二种调用 <code>specularColor()</code> 有一个可选参数，<code>color</code>。 可以传递一个 <a href="/reference/p5/p5.Color">p5.Color</a> 对象, 一个颜色值数组， 或一个 CSS 颜色字符串来设置高光颜色。</p>
请修改一下中英文符号混用的情况。

2024-04-30 17:50 UTC, sproutleaf requested changes
麻烦通篇补一下params之下type的翻译，其它都很棒，谢谢！

2024-04-30 17:50 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/ambientLight.mdx
>          type: Number
麻烦整个PR上下type补翻译一下~ 只要翻译常见type（如Number, String等）即可，不用翻译p5特有的type（比如p5.Color）

2024-04-30 23:31 UTC, sproutleaf approved these changes
很棒，感谢！

2024-05-01 10:33 UTC, unicar9 approved these changes
很棒～

2024-05-01 10:34 UTC, unicar9 commented
Hi @Qianqianye this PR is ready to merge, thanks :)

2024-05-01 19:11 UTC, merged

2024-05-01 19:11 UTC, Qianqianye commented
Looks great, thank you all!