[p5.js-es] Translate Batch 4 - Foundation
processing/p5.js-website pull request #319
Opened 2024-04-29 20:41 UTC by DianaMGalindo

Hola a todos!

Este PR contiene un avance en las traducciones de la última fase de traducciones.
Por el momento están listas para revisión:
- Array
- Boolean
- Class
- For

Gracias!

2024-04-29 21:17 UTC, holomorfo requested changes
Hola Diana, gracias por tus traducciones, te dejo algunos comentarios.
CC: @Guirdo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/Array.mdx
> +title: Arreglo
por favor no traducir contenido de
title
module
submodule

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/Array.mdx
> +  <code> let cero = colores[0]; // 'deeppink' let primero = colores[1]; // 'darkorchid' let segundo= colores[2]; // 'magenta' </code>
por favor no traducir contenido dentro de codigo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/boolean.mdx
> +title: Booleano
no traducir pf

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/boolean.mdx
> +    type: Cadena de Caracteres|Booleano|Número|Arreglo
no traducir pf

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/boolean.mdx
> +  type: Booleano
no traducir pf Booleano

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/class.mdx
> +  <p>Las clases pueden facilitar la programación con objetos. Por ejemplo, una clase <code>Rana</code> podría crear objetos que se comporten como ranas. Cada objeto creado usando una clase se llama ‘
no traducir pf contenido de codigo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/class.mdx
> +  <p>La variable <code>fifi</code> se refiere a una instancia de la clase <code>Rana</code>. La palabra clave <code>new</code> se utiliza para llamar al constructor de la clase <code>Rana</code> en l
no traducir pf contenido de codigo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/class.mdx
> +  <code> class Rana {
no traducir pf contenido de codigo, por favor revisar en todos los archivos

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/for.mdx
> +  // Bucle de izquierda a derecha (eje x).
no traducir pf contenido de codigo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/for.mdx
> +  // Crear un array de coordenadas x.
no traducir pf contenido de codigo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/for.mdx
> +  // Dibujar círculos con un bucle for.
no traducir pf contenido de codigo

2024-04-29 21:17 UTC, holomorfo commented on src/content/reference/es/p5/for.mdx
> +  // Dibujar círculos con una declaración for...of.
no traducir pf contenido de codigo

2024-04-29 21:36 UTC, Guirdo requested changes
Gracias Diana! Mis observaciones serian las mismas que las de @holomorfo . Por favor, devuelve los pedazos de código a su estado original y demás campos como title, module, submodule y el tipo de los parámetros

2024-04-29 21:36 UTC, Guirdo commented on src/content/reference/es/p5/Array.mdx
> +  <code> let colores = ['rosa intenso', 'orquídea oscura', 'magenta']; </code>
Por favor, devolver a su estado original

2024-04-30 12:45 UTC, DianaMGalindo commented
Actualización de PR: 
@holomorfo  @Guirdo Gracias por sus observaciones. He ejecutado las correcciones correspondientes para 

-  Array
- Boolean
- Class
- For

También he añadido las traducciones de:

- Function
- If
- Let
- Number
- Object
- While

**Faltante: String**

2024-04-30 16:13 UTC, DianaMGalindo commented
Hola @Guirdo ! Creo que he terminado la traducción de las referencias que se me han asignado. Dentro de String, no estoy segura sobre la traducción de ‘template literals’. No estoy segura si debería ser las ‘plantillas de literales’, o los ‘literales de plantillas’. Gracias! 
También he añadido las ultimas correcciones que sugeriste.

2024-04-30 16:30 UTC, Guirdo approved these changes
"Plantillas de literales" me parece buena traducción. 

Así que doy por aprobado  💯 tu PR. Muchas gracias!

2024-04-30 17:19 UTC, holomorfo commented
Hi @Qianqianye this PR is ready for merging.

@Guirdo

2024-04-30 17:48 UTC, merged

2024-04-30 17:49 UTC, Qianqianye commented
Looks great, thanks!