[p5.js-es] Translate Transform reference | Batch 4 Final
processing/p5.js-website pull request #320
Opened 2024-04-30 05:50 UTC by MarianneTeixido

I translated the following files:
-  Translate 
            applyMatrix()
            resetMatrix()
            rotate()
            rotateX()
            rotateY()
            rotateZ()
            scale()
            shearX()
            shearY()
            translate()

2024-04-30 07:05 UTC, holomorfo requested changes
Hola Marianne, muchas gracias por tus traducciones, the dejé un par de comentarios.
CC: @Guirdo

2024-04-30 07:05 UTC, holomorfo commented on src/content/reference/es/p5/rotateY.mdx
> +module: Events
no corresponde el nombre del modulo y submodulo y "file" puedes revisar que si sea este el archivo correcto por favor?

2024-04-30 13:46 UTC, Guirdo requested changes
Muchas gracias, Marianne! Solo dos traducciones que no corresponden en los archivos `rotateY` y `rotateZ`.

2024-04-30 13:46 UTC, Guirdo commented on src/content/reference/es/p5/rotateY.mdx
>  ---
Traducción no corresponde al archivo original

2024-04-30 13:46 UTC, Guirdo commented on src/content/reference/es/p5/rotateZ.mdx
>  ---
Traducción no corresponde

2024-05-01 02:47 UTC, MarianneTeixido commented
Corregí los comentarios en rotateY y rotateZ c:

2024-05-01 02:52 UTC, Guirdo requested changes
Gracias Marianne! Te dejo un par de observaciones

2024-05-01 02:52 UTC, Guirdo commented on src/content/reference/es/p5/rotateZ.mdx
> +itemtype: método
Devolver a su estado original, por favor

2024-05-01 02:52 UTC, Guirdo commented on src/content/reference/es/p5/rotateZ.mdx
> +ejemplo:
Devolver a su estado original

2024-05-01 02:59 UTC, MarianneTeixido commented
Listou

2024-05-01 03:01 UTC, Guirdo approved these changes
Muchas gracias! Aprobado 💯

2024-05-01 03:02 UTC, holomorfo commented
aprobado, muchas gracias 😊

2024-05-01 03:03 UTC, Guirdo commented
Hi @Qianqianye @limzykenneth ! This PR is ready! 

Thank you!

2024-05-01 03:12 UTC, MarianneTeixido commented
😊

2024-05-01 04:34 UTC, merged

2024-05-01 04:35 UTC, Qianqianye commented
Looks great, thank you all!