[p5.js hi]: Constants, Foundation and Transform References
processing/p5.js-website pull request #321
Opened 2024-04-30 10:17 UTC by SanjaySinghRajpoot

Foundation - 11 
Constants - 7 
Transform - 10

2024-04-30 14:06 UTC, Divyansh013 requested changes

2024-04-30 14:06 UTC, Divyansh013 commented on src/content/reference/hi/p5/for.mdx
> -  </ul>
this change is unnecessary imo

2024-04-30 14:06 UTC, Divyansh013 commented on src/content/reference/hi/p5/rotate.mdx
> +  <p>समन्वय प्रणाली को घुमाता है।</p>
as discussed use 'निर्देशांक' for coordinate

2024-05-01 13:32 UTC, SanjaySinghRajpoot commented on src/content/reference/hi/p5/for.mdx
> -  </ul>
can you please elaborate more on this?

2024-05-02 07:46 UTC, Divyansh013 commented
@TanviKumar PTAL

2024-05-02 08:05 UTC, TanviKumar approved these changes

2024-05-02 16:39 UTC, Divyansh013 commented
@Qianqianye @limzykenneth we can merge this PR

2024-05-02 20:26 UTC, Qianqianye commented
Hi @SanjaySinghRajpoot @Divyansh013 @TanviKumar, could you fix this PR so it could pass the checks? Thanks!

2024-05-05 11:40 UTC, TanviKumar commented
@Qianqianye you can merge this now

2024-05-06 05:20 UTC, merged

2024-05-06 05:20 UTC, Qianqianye commented
Looks great, thank you all!