[p5.js - zh-Hans] Transform (10) + Constants (7) + Events (4) : touches ~ touchEnded
processing/p5.js-website pull request #322
Opened 2024-04-30 10:38 UTC by togekisse

Total: 21 references

2024-04-30 10:41 UTC, togekisse commented
First commit: I had accidentally translated before checking if my fork had synced.

2024-04-30 18:25 UTC, sproutleaf requested changes
module, submodule, 和params下面的type都要翻译。麻烦补一下～

（ps还没有看具体的翻译内容）

2024-04-30 19:09 UTC, sproutleaf requested changes

2024-04-30 19:09 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/applyMatrix.mdx
> +<p>有两种方式可以在二维和三维中调用 <code>applyMatrix()</code>。</p>
<p>有两种方式可以在二维和三维中调用 <code>applyMatrix()</code>。</p> ->

<p><code>applyMatrix()</code> 可以在二维和三维两种场景中调用 。</p>

2024-04-30 19:09 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/constants/DEGREES.mdx
> +  <p>默认情况下，诸如 <a href="/reference/p5/rotate">rotate()</a> 和 <a href="/reference/p5/sin">sin()</a> 等函数期望以弧度为单位测量角度。
<p>默认情况下，诸如 <a href="/reference/p5/rotate">rotate()</a> 和 <a href="/reference/p5/sin">sin()</a> 等函数期望以弧度为单位测量角度。->

<p><a href="/reference/p5/rotate">rotate()</a> 和 <a href="/reference/p5/sin">sin()</a> 等函数默认以弧度为单位测量角度。

2024-04-30 19:09 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/constants/DEGREES.mdx
> +  调用 <code>angleMode(DEGREES)</code> 确保角度以弧度为单位测量。</p>
这里翻译语意有误：

angleMode(DEGREES)不是默认用法。这里是用角度，而不是弧度的。

应该翻译成：
调用 <code>angleMode(DEGREES)</code> 可以确保以角度为单位测量。</p>

2024-04-30 19:09 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/constants/RADIANS.mdx
> +  <p>默认情况下，诸如 <a href="/reference/p5/rotate">rotate()</a> 和 <a href="/reference/p5/sin">sin()</a> 等函数期望以弧度为单位测量角度。
这里请根据degrees里的建议也改一下！

2024-04-30 21:51 UTC, togekisse commented on src/content/reference/zh-Hans/p5/constants/DEGREES.mdx
> +  调用 <code>angleMode(DEGREES)</code> 确保角度以弧度为单位测量。</p>
没有看到你指出的语意有误这一段，能不能再确认一下啦~

2024-04-30 23:37 UTC, sproutleaf requested changes

2024-04-30 23:37 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/constants/DEGREES.mdx
> +  调用 <code>angleMode(DEGREES)</code> 确保角度以弧度为单位测量。</p>
嗯~ 原文这段：

By default, functions such as rotate() and sin()expect angles measured in units of radians.
Calling angleMode(DEGREES) ensures that angles are measured in units of  degrees.

rotate和sin之类的函数默认取弧度(radians)。用angleMode(DEGREES)可以切换成度数(degrees)。

你上面的翻译里前后用的都是弧度，没有写明radians和degrees之间的区别！

2024-05-01 10:43 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/touches.mdx
> +  <p>屏幕设备上所有当前触摸点的 <code>Array</code>。</p>
屏幕设备上所有当前触摸点的 <code>Array</code>。-> 包含一个触摸屏设备上所有当前触摸点的一个数组  <code>Array</code>。

2024-05-01 10:46 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/touches.mdx
> +  <p><code>touches</code> 数组默认为空。当用户屏幕幕时，会跟踪新的触摸点并将其添加到数组中。触摸点具有以下属性 <code>Objects</code>：</p>
当用户屏幕幕时，会跟踪新的触摸点并将其添加到数组中。-> 当用户触摸屏幕时，一个新的触摸点会被追踪并添加到这个数组中。

触摸点具有以下属性 <code>Objects</code>：-> 触摸点是带有以下属性的对象 <code>Objects</code>：

2024-05-01 10:48 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/touchStarted.mdx
> +  <p>每当用户屏幕幕时调用的函数。</p>
每当用户屏幕幕时调用的函数。-> 每当用户触摸屏幕时调用的函数。

2024-05-01 10:50 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/touchMoved.mdx
> +  <p>当用户屏幕幕并移动时调用的函数。</p>
当用户屏幕幕并移动时调用的函数。-> 当用户触摸屏幕并移动时调用的函数。

2024-05-01 10:52 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/touchEnded.mdx
> +  <p>声明函数 <code>touchEnded()</code> 会设置一个代码块，在用户停止屏幕幕设备时自动运行：</p>
在用户停止屏幕幕设备时自动运行：-> 在用户停止触摸触屏设备时自动运行：

2024-05-01 10:53 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/shearY.mdx
> +  函数转换坐标系，平移y 坐标，而 x 坐标保持不变。</p>
平移y 坐标 -> 平移 y 坐标

有些中英文空格不一致。

2024-05-01 10:56 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/scale.mdx
> +  <p>第一种调用 <code>scale()</code> 的方式使用数字来设置缩放量。第一个参数 <code>s</code> 设置每个轴的缩放量。例如，调用 <code>scale(2)</code> 将 x 轴、y 轴和 z 轴拉伸2倍。接下来的两个参数 <code>y</code> 和 <code>z</code> 是可选的。它们设置 y 轴和 z 轴的缩放量。例如，调用 <code
将x轴拉伸2倍，y轴缩小 0.5 倍 -> 将 x 轴拉伸 2 倍，y 轴缩小 0.5 倍

2024-05-01 11:00 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/rotate.mdx
> +<p>第一个参数 <code>angle</code> 是旋转的角度。例如，调用 <code>rotate(1)</code> 将坐标系顺时针旋转1弧度，约为57度。<code>rotate()</code> 根据当前的 <a href="/reference/p5/angleMode">angleMode()</a> 解释角度值。</p>
调用 <code>rotate(1)</code> 将坐标系顺时针旋转1弧度，约为57度。-> 调用 <code>rotate(1)</code> 将坐标系顺时针旋转 1 弧度，约为 57 度。

2024-05-01 11:02 UTC, unicar9 commented on src/content/reference/zh-Hans/p5/constants/HALF_PI.mdx
> +  <p>一个<code>Number</code>常量，约为1.5708。</p>
约为1.5708。-> 约为 1.5708。

2024-05-02 00:11 UTC, sproutleaf requested changes

2024-05-02 00:11 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/rotate.mdx
>      type: 'p5.Vector|Number[]'
麻烦Number[]改成字符串[]!

2024-05-02 00:11 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/scale.mdx
>          type: 'Number|p5.Vector|Number[]'
'Number|p5.Vector|Number[]' -> '数字|p5.Vector|数字[]'

2024-05-02 00:11 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/scale.mdx
>          type: 'p5.Vector|Number[]'
'p5.Vector|Number[]' -> 'p5.Vector|数字[]'

2024-05-02 21:02 UTC, sproutleaf requested changes

2024-05-02 21:02 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/rotate.mdx
> +    type: 'p5.Vector|字符串[]'
这里是数字，不是字符串

2024-05-02 21:02 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5/touchMoved.mdx
> +  <p>当用户屏幕幕并移动时调用的函数。</p>
这里的typo还没改～

2024-05-03 18:42 UTC, Qianqianye commented
Thanks @togekisse @sproutleaf @unicar9. Could you also fix this PR so it could pass the checks? Thank you!

2024-05-04 22:59 UTC, unicar9 approved these changes

2024-05-06 05:22 UTC, merged

2024-05-06 05:22 UTC, Qianqianye commented
Looks great, thank you all!