[p5.js - zh-Hans] Added translations for camera ~ p5.Camera.slerp
processing/p5.js-website pull request #323
Opened 2024-04-30 12:52 UTC by douMax

2024-04-30 17:41 UTC, sproutleaf requested changes
麻烦整个PR有type的地方补一下翻译！只要补常见type（Number, Boolean)即可，不用翻译p5专有type（比如p5.Camera)

其它都很好，谢谢！

2024-04-30 17:41 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5.Camera/camera.mdx
>      type: Number
type也是要翻译的，请整个PR统一一下， 谢谢！

2024-04-30 17:41 UTC, sproutleaf commented on src/content/reference/zh-Hans/p5.Camera/move.mdx
>    - name: 'y'
这里应该原文有误，可以把单引号去掉

2024-05-01 11:24 UTC, douMax commented
均已修改 
@sproutleaf @unicar9

2024-05-01 11:28 UTC, unicar9 approved these changes
很棒！

2024-05-02 00:12 UTC, sproutleaf approved these changes
Approve, tagging @limzykenneth @Qianqianye for merge. Thank you!

2024-05-02 20:24 UTC, merged

2024-05-02 20:25 UTC, Qianqianye commented
Looks great, thank you all!