[p5.js KO] update korean translation (Foundation, 3D)
processing/p5.js-website pull request #325
Opened 2024-04-30 18:48 UTC by YewonCALLI

2024-05-01 01:51 UTC, designerSejinOH commented
@YewonCALLI 1차 리뷰 및 yaml 구문 오류 해결중입니다!

2024-05-01 05:01 UTC, designerSejinOH commented
@YewonCALLI  진짜 어마어마한 양이었는데 번역하시느라 고생하셨습니다...! 구문 오류 해결(1개 제외) 및  1차 리뷰, 수정 완료하였습니다!! @yinhwa 오래 기다리셨습니다,,, ㅜ 2차 리뷰 바로 진행해주시면 될 것 같아요!! 감사합니다!!

2024-05-01 10:44 UTC, yinhwa commented
@YewonCALLI @designerSejinOH 예원님 세진님 고퀄로 번역 + 1차리뷰 진행하시느라 고생많으셨습니다!! 일부 표현에 한해 다른 번역자님들과 톤맞추는 정도의 마이너한 수정사항 밖에 없어, 예원님께서는 제게 [예원님 로컬 리포](https://github.com/YewonCALLI/p5.js-website/tree/patch-4)에 대한 collaborator (쓰기 포함) 권한 주시면 이 점 반영한 후 승인처리하고자 합니다 :)

2024-05-01 11:50 UTC, YewonCALLI commented
@yinhwa 넵!! 권한 초대드렸습니다!! 감사해요🥰

2024-05-01 15:22 UTC, yinhwa approved these changes
Hi @Qianqianye @limzykenneth we're approving this PR; and yet it's going through some build issues, which @designerSejinOH has strived to fix 😅 We'd love to ask for your help in this. Kindly let us know if there's anything we can do. Thank you very much! 

2차 리뷰 및 수정 (22:10-00:14, 총 2시간 14분) 완료하였습니다. 예원님과 세진님의 고심이 여실히 느껴지는 결과물입니다...^^* 고퀄로 잘해주셔서 정말 다시 한번 감사드리고, 승인 처리합니다. @YewonCALLI @designerSejinOH

2024-05-01 15:22 UTC, yinhwa commented on src/content/reference/ko/p5/createFilterShader.mdx
는 혹시 몰라서 일단 원복해두었고, 대신 같은 문장 내 동일 한글 단어에 (영문병기)해두었습니다 :)

2024-05-08 12:35 UTC, limzykenneth requested changes
There is a merge conflict in `shader.mdx` can you have a look and resolve it? Then I can merge this. Thanks.

2024-05-08 12:35 UTC, limzykenneth commented on src/content/reference/ko/p5/function.mdx
> +description: "<p>함수는 명령문들의 묶음을 지칭하는 이름입니다.</p>\n<p><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions" target="_blank">Functions</a>는 코드를 조직하고 재사용하는 데 도움을 줍니다. 예를 들어, 함수
```suggestion
description: > 
  <p>함수는 명령문들의 묶음을 지칭하는 이름입니다.</p>\n<p><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions" target="_blank">Functions</a>는 코드를 조직하고 재사용하는 데 도움을 줍니다. 예를 들어, 함수를 사용하면 "꽃 그리기"라는 아이디어를 쉽게 표현할 수 있습니다.</p>\n<code>\nfunction drawFlower() {\n  // Style the text.\n  textAlign(CENTER, CENTER);\n  textSize(20);\n\n<p>  // Draw a flower emoji.\n  text('\U0001F338', 50, 50);\n}\n</p></code>\n<p>함수 도입부는 <code>function</code> 키워드로 시작합니다. 함수의 이름인 <code>drawFlower</code> 뒤에는 소괄호 <code>()</code>와 중괄호 <code>{}</code>가 따릅니다.\n 중괄호 사이의 코드를 함수의 본문이라고 합니다. 함수의 본문은 다음과 같이 함수가 호출될 때 실행됩니다:</p>\n<code>\ndrawFlower();\n</code>\n\n<p>함수는 도입부에 매개변수를 추가함으로써 입력을 받을 수 있습니다. 매개변수는 함수가 호출될 때 제공될 값의 자리 표시자입니다. 예를 들어, <code>drawFlower()</code> 함수는 꽃의 크기에 대한 매개변수를 포함할 수 있습니다:</p>\n<code>\nfunction drawFlower(size) {\n  // Style the text.\n  textAlign(CENTER, CENTER);\n\n<p>  // Use the size parameter.\n  textSize(size);</p>\n<p>  // Draw a flower emoji.\n  text('\U0001F338', 50, 50);\n}\n</p></code>\n<p>매개변수는 함수 선언의 일부입니다. 인수는 함수를 호출하는 코드에 의해 제공됩니다. 함수가 호출될 때, 인수는 매개변수에 할당됩니다:</p>\n<code>\n// The argument 20 is assigned to the parameter size.\ndrawFlower(20);\n</code>\n\n<p>함수는 여러 매개변수를 쉼표로 구분하여 가질 수 있습니다. 매개변수는 어떤 유형이든 될 수 있습니다. 예를 들어, <code>drawFlower()</code> 함수는 꽃의 x좌표와 y좌표 및 크기에 대한 <code>Number</code> 매개변수를 받아들일 수 있습니다:</p>\n<code>\nfunction drawFlower(x, y, size) {\n  // Style the text.\n  textAlign(CENTER, CENTER);\n\n<p> // Use the size parameter.\n  textSize(size);</p>\n<p>  // Draw a flower emoji.\n  // Use the x and y parameters.\n  text('\U0001F338', x, y);\n}\n</p></code>\n<p>함수는 <code>return</code> 문을 추가함으로써 출력을 생성할 수도 있습니다:</p>\n<code>\nfunction double(x) {\n  let answer = 2 * x;\n  return answer;\n}\n</code>\n\n<p><code>return</code> 뒤의 표현식은 다른 곳에서 사용될 수 있는 출력을 생성할 수 있습니다. 예를 들어, <code>double()</code> 함수의 출력은 변수에 할당될 수 있습니다:</p>\n<code>\nlet six = double(3);\ntext(`3 x 2 = ${six}`, 50, 50);\n</code>
```

2024-05-08 12:35 UTC, limzykenneth commented on src/content/reference/ko/p5/function.mdx
> +description: "<p>함수는 명령문들의 묶음을 지칭하는 이름입니다.</p>\n<p><a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions" target="_blank">Functions</a>는 코드를 조직하고 재사용하는 데 도움을 줍니다. 예를 들어, 함수
This should fix the build error.

2024-05-08 14:05 UTC, designerSejinOH commented
@limzykenneth We have resolved the conflict and build error! Please check and let me know if there are any issues! Thank you! @YewonCALLI @yinhwa

2024-05-08 18:04 UTC, limzykenneth approved these changes

2024-05-08 18:04 UTC, merged