Fix broken links on contributor page readme
processing/p5.js-website pull request #448
Opened 2024-07-08 02:41 UTC by sambensim

- Fixed 6 links as outlined in Issue #444.

- Additionally fixed a typo in the second to last paragraph (changed from "there are many more ways to contribute to p5.js through non-source code contribution than can be exhaustively listed here" to "there are many more ways to contribute to p5.js through non-source code contribution than ***cannot*** be exhaustively listed here").

2024-07-08 02:43 UTC, sambensim commented
@all-contributors please add @sambensim for 📖 doc

2024-07-17 12:10 UTC, limzykenneth requested changes
A couple fixes in the line comments.

2024-07-17 12:10 UTC, limzykenneth commented on src/content/contributor-docs/en/README.mdx
> +You can find relevant contribution type [here](https://allcontributors.org/docs/en/emoji-key). Although we will usually automatically add you to the contributor list using the bot after merging your
```suggestion
You can find relevant contribution type [here](https://allcontributors.org/docs/en/emoji-key). Although we will usually automatically add you to the contributor list using the bot after merging your PR. The contributor docs are published on p5.js [website](https://p5js.org/contribute/), and hosted on p5.js [GitHub repository](https://github.com/processing/p5.js/tree/main/contributor_docs).
```

2024-07-17 12:10 UTC, limzykenneth commented on src/content/contributor-docs/en/README.mdx
> +There are many more ways to contribute to p5.js through non-source code contribution than cannot be exhaustively listed here, some of the ways may also involve working with some of the p5.js reposito
I think the original is correct here

2024-08-05 12:18 UTC, SableRaf commented on src/content/contributor-docs/en/README.mdx
> +There are many more ways to contribute to p5.js through non-source code contribution than cannot be exhaustively listed here, some of the ways may also involve working with some of the p5.js reposito
Agreed. I can see why the original phrasing could be seen as confusing though. 

We could rephrase this in a more readable and to the point format. How about this: 

`There are many ways to contribute to p5.js beyond coding, such as adding examples, writing tutorials for the website and more. If you need help getting involved, contact us through the official [p5.js Discord](https://discord.gg/SHQ8dH25r9) or the [Processing Foundation forum](https://discourse.processing.org/c/p5js/10).`

I also clarified the CTA and added a link to Discord.

2024-08-21 11:10 UTC, SableRaf commented
@sambensim would you mind revising this PR to focus only on the fixes to the broken links? 

Feel free to open a separate issue for the copy. Though it is not a typo, the text could be made clearer (see my inline comment).

2024-08-26 17:43 UTC, sambensim commented
> @sambensim would you mind revising this PR to focus only on the fixes to the broken links?
> 
> Feel free to open a separate issue for the copy. Though it is not a typo, the text could be made clearer (see my inline comment).

Hey! Sorry just saw this, should I use the text you suggested earlier or just focus on the link fixes?

2024-08-26 18:10 UTC, SableRaf commented
@sambensim No worries! Thanks for your reply :) I'd suggest focusing on the links. 

If you want to address the text please open a separate issue. It is correct as is but your intuition to correct it shows that the phrasing could be clearer.

2024-09-08 06:50 UTC, Qianqianye commented
Thanks @sambensim for all your work on this. The [contribute](https://p5js.org/contribute/) pages on p5js.org website are built directly from p5.js library repo [contributor_docs](https://github.com/processing/p5.js/tree/main/contributor_docs) folder. So if we want to make changes, we will edit the docs in p5.js library repo [contributor_docs](https://github.com/processing/p5.js/tree/main/contributor_docs) folder,

All the broken links mentioned in this PR is fixed in this [commit](https://github.com/processing/p5.js/commit/3c86d93ee183118f534ea1471ae9be2f22423d18) in p5.js library repo, and then this [commit](https://github.com/processing/p5.js-website/commit/64b2becffcb89f2f4d3c969fee27066b0d205e8e) in p5.js website repo. In the future, if you find more broken links of contribute pages, please go ahead and open PRs within [p5.js library repo](https://github.com/processing/p5.js). 

I will close this PR for organizational purpose. Thank you!

2024-09-08 06:50 UTC, closed without merging